
dist: xenial
language: python
python: 3.7
install:
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - flake8 --config=setup.cfg
  - mypy --config=setup.cfg src/
  - python -m pytest --verbose tests/
